### ISSUE TITLE
Installation Instructions in index.md don't work

### ISSUE THREAD

**Issue by josefsabl** [NasExt/DependentSelectBox#19]
NasExt\Forms\Extension::registerControls(); does not exist.

**Comment by aleswita** [comment]
Hi @josefsabl, tnx for report this issue, use **NasExt\Forms\DependentExtension::registerControls();**

Closed https://github.com/NasExt/DependentSelectBox/commit/c43982b1c592ee4abe19475e1d5af4edf20d8a4d

**Comment by josefsabl** [comment]
I now noticed this weird sentence. My guess is copy paste error? :-)

'The best way to install AlesWita/DropzoneUploader is using Composer:'


Here: https://github.com/NasExt/DependentSelectBox/blob/c43982b1c592ee4abe19475e1d5af4edf20d8a4d/doc/index.md

**Comment by aleswita** [comment]
You are right, copy paste error :-)
