### ISSUE TITLE
DependentSelectBox not work in WebChemistry/Multiplier

### ISSUE THREAD

**Issue by duskohu** [NasExt/DependentSelectBox#21]
[in forum](https://forum.nette.org/cs/24600-nasext-dependentselectbox#p191675)

**Comment by aleswita** [comment]
Nyni jsem poprve potreboval vytvorit dependent select s kombinaci [Kdyby/FormsReplicator](https://github.com/Kdyby/FormsReplicator) a posledni verze 3.1.1. funguje spravne.

**Comment by aleswita** [comment]
seems solved => https://github.com/WebChemistry/forms-multiplier/issues/12
