### ISSUE TITLE
AJAX request fired multiple times

### ISSUE THREAD

**Issue by teekey99** [NasExt/DependentSelectBox#28]
Today, I implemented this neat library into my project. The implementation itself was very simple. However, one head-scratcher occurred. I have a form in which there are 3 dependent select boxes, each dependent on:

- the very first select box (without any dependency) in the form
- one checkbox toggling `true` / `false` variant
- value from previous dependent select box

When I make a change to any of registered parents, the AJAX request gets fired as many times as the count of all select boxes that need to be changed due to a change of their respective parents. Every change made to the form therefor takes a ridiculous amount of time and slows down the development and testing.

Is this a standard behavior or should this extension be able to get all the data in single request?

**Comment by aleswita** [comment]
Hi, in dev speed is lazy (tracy reloaded request by request), its true. But in production mode its ok. I have forms with 5 dependent boxes and changes are instant.

**Comment by teekey99** [comment]
@aleswita Thanks for your reply. I have tried it in production mode as well and yes, it is much faster. Anyway, I would like to know if it's intended that there are separate AJAX requests for each select box. The client-side code looks like it is expected behavior, I just want to be sure I'm not doing anything wrong.

**Comment by aleswita** [comment]
Yes, its expected behavior.
