### ISSUE TITLE
pouziti v komponente

### ISSUE THREAD

**Issue by hurycz** [NasExt/DependentSelectBox#8]
pokud mam komponentu a v ni vytvarim formular, spatne se predavaji parametry

?do=menuItemForm-menuForm-menu-load&**locale=cs**

u **locale** chybi prefix, do ktere komponenty se ma parametr predat

**Comment by ondraondra81** [comment]
Locale je "global (stejna pro cely web)" do komponenty pokud bys sis měl předávat Translator jako závislost a když už locale tak jako parametr pro factory, takže to chyba není
