### ISSUE TITLE
problem se zanorenym selectem

### ISSUE THREAD

**Issue by hurycz** [NasExt/DependentSelectBox#9]
mam:
```
$form->addDependentSelectBox... function(){

$data = new DependentSelectBoxData();

$menu['Skupina 1'][1] = '1.1';
$menu['Skupina 1'][2] = '1.2';
$menu['Skupina 1'][3] = '1.3';

$menu['Skupina 2'][7] = '2.1';
$menu['Skupina 2'][8] = '2.2';
$menu['Skupina 2'][9] = '2.3';

return $data->setItems($menu);
}
```

mi vypise
![image](https://cloud.githubusercontent.com/assets/8737590/18440454/79e0999c-7909-11e6-9b79-5ed2ea9964c7.png)

- normalni selectbox takto funguje... https://doc.nette.org/cs/2.4/forms#toc-addselect-name-label-null-array-items-null
- chyba nastava pouze, kdyz se data pro dependent select nacitaji ajaxem... 

pokud by to nebylo jasne, napisu vice podrobnosti...

**Comment by duskohu** [comment]
Thx
